import 'package:communal_mobile/cubits/obligation_categories/obligation_categories_cubit.dart';
import 'package:communal_mobile/data/local/home_wallet_prefs.dart';
import 'package:communal_mobile/data/local/kyc_progress_storage.dart';
import 'package:communal_mobile/data/local/theme_mode_controller.dart';
import 'package:communal_mobile/data/local/transfer_favorites_prefs.dart';
import 'package:communal_mobile/data/repositories/account_actions_repository.dart';
import 'package:communal_mobile/data/repositories/community_repository.dart';
import 'package:communal_mobile/core/services/pending_deep_link_service.dart';
import 'package:communal_mobile/core/services/unread_notifications_service.dart';
import 'package:communal_mobile/data/repositories/notifications_repository.dart';
import 'package:communal_mobile/data/repositories/obligation_categories_repository.dart';
import 'package:communal_mobile/data/repositories/profile_repository.dart';
import 'package:communal_mobile/data/repositories/transfer_repository.dart';
import 'package:communal_mobile/core/utils/device_label_service.dart';
import 'package:communal_mobile/data/datasources/remote/dio/dio_client.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'injection.config.dart'; // generated by build_runner

final GetIt getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  await getIt.init(); // calls the generated config

  // Resolve device label in background; update User-Agent once ready.
  // Fire-and-forget: the first login request may still use the basic
  // platform-only UA, but all subsequent requests get the full label.
  getDeviceLabel().then((label) {
    getIt<DioClient>().updateUserAgent(label);
  });
  // Defensive: injectable has occasionally emitted duplicate [KycProgressStorage] module
  // providers, which can leave GetIt without a resolvable registration.
  if (!getIt.isRegistered<KycProgressStorage>()) {
    getIt.registerLazySingleton<KycProgressStorage>(
      () => KycProgressStorage(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<HomeWalletPrefs>()) {
    getIt.registerLazySingleton<HomeWalletPrefs>(
      () => HomeWalletPrefs(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<ThemeModeController>()) {
    getIt.registerLazySingleton<ThemeModeController>(
      () => ThemeModeController(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<TransferRepository>()) {
    getIt.registerLazySingleton<TransferRepository>(
      () => TransferRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<CommunityRepository>()) {
    getIt.registerLazySingleton<CommunityRepository>(
      () => CommunityRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<NotificationsRepository>()) {
    getIt.registerLazySingleton<NotificationsRepository>(
      () => NotificationsRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<UnreadNotificationsService>()) {
    getIt.registerLazySingleton<UnreadNotificationsService>(
      () => UnreadNotificationsService(getIt()),
    );
  }
  if (!getIt.isRegistered<PendingDeepLinkService>()) {
    getIt.registerLazySingleton<PendingDeepLinkService>(
      () => PendingDeepLinkService(),
    );
  }
  if (!getIt.isRegistered<ProfileRepository>()) {
    getIt.registerLazySingleton<ProfileRepository>(
      () => ProfileRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<AccountActionsRepository>()) {
    getIt.registerLazySingleton<AccountActionsRepository>(
      () => AccountActionsRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<TransferFavoritesPrefs>()) {
    getIt.registerLazySingleton<TransferFavoritesPrefs>(
      () => TransferFavoritesPrefs(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<ObligationCategoriesRepository>()) {
    getIt.registerLazySingleton<ObligationCategoriesRepository>(
      () => ObligationCategoriesRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<ObligationCategoriesCubit>()) {
    getIt.registerLazySingleton<ObligationCategoriesCubit>(
      () => ObligationCategoriesCubit(getIt()),
    );
  }
}
