import 'package:communal_mobile/cubits/server_status/server_status_cubit.dart';
import 'package:communal_mobile/data/datasources/remote/dio/dio_client.dart';
import 'package:communal_mobile/data/datasources/remote/dio/server_status_interceptor.dart';
import 'package:communal_mobile/data/local/home_wallet_prefs.dart';
import 'package:communal_mobile/data/local/kyc_progress_storage.dart';
import 'package:communal_mobile/data/local/theme_mode_controller.dart';
import 'package:communal_mobile/data/local/transfer_favorites_prefs.dart';
import 'package:communal_mobile/data/repositories/account_actions_repository.dart';
import 'package:communal_mobile/data/repositories/community_repository.dart';
import 'package:communal_mobile/data/repositories/notifications_repository.dart';
import 'package:communal_mobile/data/repositories/profile_repository.dart';
import 'package:communal_mobile/data/repositories/transfer_repository.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'injection.config.dart'; // generated by build_runner

final GetIt getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  await getIt.init(); // calls the generated config
  // Defensive: injectable has occasionally emitted duplicate [KycProgressStorage] module
  // providers, which can leave GetIt without a resolvable registration.
  if (!getIt.isRegistered<KycProgressStorage>()) {
    getIt.registerLazySingleton<KycProgressStorage>(
      () => KycProgressStorage(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<HomeWalletPrefs>()) {
    getIt.registerLazySingleton<HomeWalletPrefs>(
      () => HomeWalletPrefs(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<ThemeModeController>()) {
    getIt.registerLazySingleton<ThemeModeController>(
      () => ThemeModeController(getIt<SharedPreferences>()),
    );
  }
  if (!getIt.isRegistered<TransferRepository>()) {
    getIt.registerLazySingleton<TransferRepository>(
      () => TransferRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<CommunityRepository>()) {
    getIt.registerLazySingleton<CommunityRepository>(
      () => CommunityRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<NotificationsRepository>()) {
    getIt.registerLazySingleton<NotificationsRepository>(
      () => NotificationsRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<ProfileRepository>()) {
    getIt.registerLazySingleton<ProfileRepository>(
      () => ProfileRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<AccountActionsRepository>()) {
    getIt.registerLazySingleton<AccountActionsRepository>(
      () => AccountActionsRepository(getIt()),
    );
  }
  if (!getIt.isRegistered<TransferFavoritesPrefs>()) {
    getIt.registerLazySingleton<TransferFavoritesPrefs>(
      () => TransferFavoritesPrefs(getIt<SharedPreferences>()),
    );
  }

  // Server-status: registered manually so this checkout doesn't need a
  // build_runner pass to wire up the new cubit/interceptor. The
  // interceptor is attached to the live DioClient.dio AFTER the
  // refresh interceptor (so it observes the *final* outcome of a
  // request — refreshed retries are visible to it as success, not the
  // original 401).
  if (!getIt.isRegistered<ServerStatusCubit>()) {
    getIt.registerLazySingleton<ServerStatusCubit>(() => ServerStatusCubit());
  }
  if (!getIt.isRegistered<ServerStatusInterceptor>()) {
    getIt.registerLazySingleton<ServerStatusInterceptor>(
      () => ServerStatusInterceptor(getIt<ServerStatusCubit>()),
    );
  }
  final dioClient = getIt<DioClient>();
  final statusInterceptor = getIt<ServerStatusInterceptor>();
  if (!dioClient.dio.interceptors.contains(statusInterceptor)) {
    dioClient.dio.interceptors.add(statusInterceptor);
  }
}
