import 'package:communal_mobile/data/local/kyc_progress_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'injection.config.dart'; // generated by build_runner

final GetIt getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  await getIt.init(); // calls the generated config
  // Defensive: injectable has occasionally emitted duplicate [KycProgressStorage] module
  // providers, which can leave GetIt without a resolvable registration.
  if (!getIt.isRegistered<KycProgressStorage>()) {
    getIt.registerLazySingleton<KycProgressStorage>(
      () => KycProgressStorage(getIt<SharedPreferences>()),
    );
  }
}
